#ifndef MODEL_ERROR_T
#define MODEL_ERROR_T

typedef enum
{
  ALL_OK, // :)
  IO_BAD_FILENAME,
  IO_READ_ERROR,
  IO_WRITE_ERROR,
  UNKNOWN_COMMAND,
  NO_MODEL,
  IO_BAD_STREAM,
  FILE_BAD_PT_LEN,
  FILE_BAD_PT,
  FILE_BAD_CON_LEN,
  FILE_BAD_CON,
  NO_MEMORY,
  IO_MODEL_NOT_EMPTY,
  NO_PT_ARR,
  NO_CON_ARR,
  PRINT_ERROR,
  TRANSFORM_NO_POINT,
  TRANSFORM_NO_ORIGIN,
  TRANSFORM_NO_DATA,
  TRANSFORM_NO_MODEL,
  DRAW_NO_MODEL,
  DRAW_NO_UI,
  DRAW_NO_SCENE,
  DRAW_NO_CONTEXT,
  MODEL_BAD_CONNECTION,
  MODEL_BAD_POINT,
} error;

#endif
