#ifndef MY_ERROR_T
#define MY_ERROR_T

typedef enum
{
    ALL_OK, // :)
    IO_BAD_FILENAME,
    IO_READ_ERROR,
    IO_WRITE_ERROR,
    UNKNOWN_COMMAND,
    NO_GRAPH,
    IO_BAD_STREAM,
    FILE_BAD_PT_LEN,
    FILE_BAD_PT,
    FILE_BAD_CON_LEN,
    FILE_BAD_CON,
    NO_MEMORY,
    PT_ARR_NOT_NULL,
    CON_ARR_NOT_NULL,
    PT_NOT_NULL,
    CON_NOT_NULL,
    IO_GRAPH_NOT_EMPTY,
    NO_PT_ARR,
    PRINT_ERROR,
    TRANSFORM_NO_POINT,
    TRANSFORM_NO_ORIGIN,
    TRANSFORM_NO_DATA,
    TRANSFORM_NO_GRAPH,
    DRAW_NO_GRAPH,
    DRAW_NO_UI,
    DRAW_NO_SCENE,
    DRAW_NO_CONTEXT,
    GRAPH_BAD_CONNECTION,
    GRAPH_BAD_POINT,
} my_error;

#endif
